name: Capturar Plantillas de Reels
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-capture:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Dependencias
        run: |
          npm init -y
          npm install puppeteer

      - name: Capturar Capturas de Pantalla
        run: |
          node <<'EOF'
          const puppeteer = require('puppeteer');
          
          (async () => {
            try {
              const browser = await puppeteer.launch({
                args: ['--no-sandbox', '--disable-setuid-sandbox']
              });
              const page = await browser.newPage();
              await page.goto('https://reanimalia-templates-i2uvtab9n-kalahan79s-projects.vercel.app/');
              
              const template1 = await page.$('.template1');
              await template1.screenshot({ path: 'template1.png' });
              
              const template2 = await page.$('.template2');
              await template2.screenshot({ path: 'template2.png' });
              
              const template3 = await page.$('.template3');
              await template3.screenshot({ path: 'template3.png' });
              
              await browser.close();
            } catch (error) {
              console.error('Captura de pantalla fallida:', error);
              process.exit(1);
            }
          })();
          EOF

      - name: Subir Capturas de Pantalla
        uses: actions/upload-artifact@v4
        with:
          name: capturas-de-plantillas
          path: '*.png'
          retention-days: 5
